project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Zhiqiang Wang"
  site-url: https://zhiqiangwang.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/LuoChenq/zhiqiangwang.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
      [Zhiqiang Wang](https://github.com/LuoChenq/zhiqiangwang.github.io)<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Background"
        href: background.qmd
      - text: "Research"
        href: publications.qmd
      - text: "Projects"
        href: project.qmd 
      - text: "CV"
        href: CV_EN.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细